env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
rules: { "react/react-in-jsx-scope": "off", "react/prop-types": 0 }
ignorePatterns: ["node_modules/", "dist/", "__tests__/"] #
settings:
  react:
    version: "detect"
