name: Deploy

on:
  push:
    branches: [main]

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_IAM_ROLE_NAME: ${{ secrets.AWS_IAM_ROLE_NAME }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  VITE_INTERNAL_API_BASE_URL: ${{ secrets.VITE_INTERNAL_API_BASE_URL }}
  VITE_GITHUB_CLIENT_ID: ${{ secrets.VITE_GITHUB_CLIENT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          echo "VITE_INTERNAL_API_BASE_URL=${{ env.VITE_INTERNAL_API_BASE_URL }}" > .env.production
          echo "VITE_GITHUB_CLIENT_ID=${{ env.VITE_GITHUB_CLIENT_ID }}" >> .env.production
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "us-east-1"
          role-to-assume: "arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_IAM_ROLE_NAME }}"

      - name: Deploy to S3
        run: |
          aws s3 cp --recursive --region ${AWS_DEFAULT_REGION} ./dist s3://${S3_BUCKET}
